### ISSUE TITLE
Hovering over Tooltip Text pushes down the bottom text.

### ISSUE THREAD

**Issue by aromalanil** [IVORY-UI/ivory#10]
* **Do you want to request a *feature* or report a *bug*?**

I want to report a bug.

* **What is the current behaviour?**

When we hover over a text having a tooltip, The line below the text is pushed to downwards a little bit.

* **If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

In the documentation, page go to the tooltip section under Components and hover over a tooltip and observe the line below it.

* **What is the expected behaviour?**

* **What is the motivation/use case for changing the behaviour?**

* **Please tell us about your environment:**  
  - Version: 
  - Browser: 

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by kanthvallampati** [comment]
Issue resolved.
