### ISSUE TITLE
Selectbox arrow icon does not work.

### ISSUE THREAD

**Issue by artlantis** [IVORY-UI/ivory#9]
* **Do you want to request a *feature* or report a *bug*?**
- Bug

* **What is the current behavior?**
- In the selectbox, arrow icon does not work. We need to click the box instead of the icon.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
- Just click the select box

* **Please tell us about your environment:**  
  - Version: v75
  - Browser: Firefox
  - OS : Windows 10 x64

**Comment by kanthvallampati** [comment]
@artlantis The icon is just an indicator which tells that it is a dropdown select, but not a click handler. Usually for the select box the click handler should not be restricted to the icon.

So I'm closing the defect.
